<?php

namespace Yoweli\LaravelScaffold\Services;

use Yoweli\LaravelScaffold\Repositories\ModelRepository;

/**
 * class ScaffoldingService
 */
class ScaffoldingService
{

    /**
     * clear the initially created migrations if any
     */
    public static function clearMigrations()
    {
        $dir = base_path() . '/database/migrations/';
        $files = scandir($dir);

        if (is_array($files)) {

            foreach ($files as $file) {

                if (is_file($dir . $file) && strpos($file, 'autogenerated')) {
                    unlink($dir . $file);
                }
            }
        }
    }

    /**
     * Backup the routes file as a new some URLs will be created
     */
    public static function backupRoutesFile()
    {
        $dir = base_path() . '/routes/';
        $files = scandir($dir);

        if (is_file(__DIR__ . '/bkp/web.php')) {
            return;
        }

        if (is_array($files)) {

            foreach ($files as $file) {

                if (is_file($dir . $file) && $file === 'web.php') {
                    copy($dir . $file, __DIR__ . '/bkp/web.php');
                }
            }
        }
    }

    /**
     * @param $projectId
     * @return array
     */
    public static function getPreparedModels($projectId): array
    {
        $modelsArray = [];
        $models = ModelRepository::getModelsForProject($projectId);

        foreach ($models as $model) {
            $modelsArray[] = $model['name'];
        }

        return $modelsArray;
    }

    /**
     * @param $data
     */
    public static function createFile($data)
    {

        if (Str::contains($data->path, 'migrations') || Str::contains($data->path, 'resources')) {

            $filePath = base_path() . $data->path;

        } elseif (Str::contains($data->path, 'routes')) {

            $fp = fopen(base_path() . $data->path . "$data->name.php", 'a');
            fwrite($fp, $data->content);
            fclose($fp);
            return;

        } else {

            $filePath = app_path() . $data->path;
        }

        if (!file_exists($filePath)) {
            mkdir($filePath, 0755, true);
        }

        file_put_contents($filePath . "$data->name.php", $data->content);
    }
}
